[core]
	engine = sqlite

[target "remotehiro"]
  uri = db:sqlite:remotehiro.db
  registry = migrations.db
  top_dir = sql/migrations

[target "remotehiro-data"]
  uri = db:sqlite:remotehiro.db
  registry = data-migrations.db
  top_dir = sql/data_migrations

[target "remotehiro-warehouse"]
  uri = db:sqlite:warehouse.db
  registry = warehouse-migrations.db
  top_dir = sql/warehouse_migrations
