[package]
name = "tag"
edition.workspace = true
homepage.workspace = true
include.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
model.workspace = true

serde_json.workspace = true

rusqlite.workspace = true
