[package]
name = "server"
edition.workspace = true
homepage.workspace = true
include.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
model.workspace = true
job.workspace = true
warehouse.workspace = true
database.workspace = true

su_sqlite.workspace = true
su_template.workspace = true

axum.workspace = true
rusqlite.workspace = true
minijinja.workspace = true
minijinja-contrib.workspace = true
pulldown-cmark.workspace = true
ammonia.workspace = true
serde.workspace = true
serde_json.workspace = true
slug.workspace = true
time.workspace = true
tokio.workspace = true
tower-http.workspace = true
deadpool-sqlite.workspace = true

tracing.workspace = true
